### ISSUE TITLE
Lazy Loading Issue

### ISSUE THREAD

**Issue by zheng17** [misha130/datepicker-ionic2#16]
Hi Misha,

We recently updated our project to ionic 3 and changed all the pages to lazy loading(added one more module.ts). Right now,  every page will blow out if that page has datepicker-ionic2 included.
The main error is "Can't bind to 'Value' since it isn't a known property fo span. (ionCHanged) ='xxx' ".

Do you have any suggestion? please help.

**Comment by misha130** [comment]
Did you add the picker module to all the children modules?
The error means the picker is not part of your module. 


I never tested for lazyloading but ill do so tomorrow. 
I'll have to add a forChild for optimizations sake anyway.

**Comment by zheng17** [comment]
yeah, I tried that. The new error is BrowseModule has been loaded. I think I have to remove DatePicker from app.module.ts. I will test that again.

**Comment by misha130** [comment]
This new error said BrowserModule was loaded or not loaded? Maybe it means you need to load common modules instead?

**Comment by zheng17** [comment]
Uncaught (in promise): Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead. Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead. at g (http://localhost:8100/build/polyfills.js:3:7133)

**Comment by misha130** [comment]
Ok, thanks.I'll test but it seems I'll have to release a new build with a CommonModule instead of BrowserModule.

**Comment by misha130** [comment]
@zheng17 I tested it and didn't find a problem. In your sub page NgModule note that you are not loading BrowserModule.

**Comment by zheng17** [comment]
![image](https://cloud.githubusercontent.com/assets/25708672/25854111/8dc39dc8-3494-11e7-9119-f4efb336b8ed.png)

**Comment by zheng17** [comment]
![image](https://cloud.githubusercontent.com/assets/25708672/25854177/c51eefca-3494-11e7-9c4d-b51c9fc6e7b3.png)
Error: Uncaught (in promise): Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.
Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.
    at g (http://localhost:8100/build/polyfills.js:3:7133)
    at new BrowserModule (http://localhost:8100/build/main.js:44172:19)
    at SupRequestListPageModuleInjector.createInternal (ng:///SupRequestListPageModule/module.ngfactory.js:202:28)
    at SupRequestListPageModuleInjector.NgModuleInjector.create (http://localhost:8100/build/main.js:3910:76)
    at NgModuleFactory.create (http://localhost:8100/build/main.js:3883:18)
    at http://localhost:8100/build/main.js:63422:53
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14529)
    at Object.onInvoke (http://localhost:8100/build/main.js:4498:37)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14469)
    at n.run (http://localhost:8100/build/polyfills.js:3:9741)
    at http://localhost:8100/build/polyfills.js:3:6774
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15213)
    at Object.onInvokeTask (http://localhost:8100/build/main.js:4489:37)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15134)
    at n.runTask (http://localhost:8100/build/polyfills.js:3:10390)
    at g (http://localhost:8100/build/polyfills.js:3:7133)
    at l (http://localhost:8100/build/polyfills.js:3:6251)
    at http://localhost:8100/build/polyfills.js:3:6805
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15213)
    at Object.onInvokeTask (http://localhost:8100/build/main.js:4489:37)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15134)
    at n.runTask (http://localhost:8100/build/polyfills.js:3:10390)
    at a (http://localhost:8100/build/polyfills.js:3:5313)
    at <anonymous>

**Comment by zheng17** [comment]
Hi Misha,
I moved your code under the components of my project, and comment "BrowserModule" out from datepicker.moudule.ts. It works now. I will close this issue.

**Comment by zheng17** [comment]
Thanks.

**Comment by misha130** [comment]
I also removed BrowserModule after further testing from the git/npm. Thanks
